language: node_js
node_js:
  - 'lts/*'

before_install:
  - gem install awesome_bot

deploy:
  - provider: script
    script:
      - awesome_bot *.md --allow-redirect --white-list travis-ci,packagephobia.now
      - npm run lint
      - npm run check-typing
      - npm run coveralls
      - npm run test:mutation-report"
      - npm run prepublishOnly
    on:
      branch: master

  - provider: script
    script:
      - awesome_bot *.md --allow-redirect --white-list travis-ci,packagephobia.now
      - npm run lint
      - npm run check-typing
      - npm run test
      - npm run test:mutation-report"
      - npm run prepublishOnly
    on:
      branch: NOT master
